# Generated by Django 4.2.2 on 2023-06-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_model', '0002_alter_account_birth_day_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
