# Generated by Django 4.1.3 on 2023-06-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_model', '0003_alter_account_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='email or username'),
        ),
    ]
